### ISSUE TITLE
Not working Manjaro Linux - blender 2.80.74  

### ISSUE THREAD

**Issue by clawdelle** [AlansCodeLog/blender-debugger-for-vscode#15]
OS:  
Linux  5.0.18-1-MANJARO #1 SMP PREEMPT Wed May 22 17:35:29 UTC 2019 x86_64 GNU/Linux

Add-on Version:
bl_info = {
   'name': 'Debugger for VS Code',
   'author': 'Alan North',
   'version': (0, 3, 0),
   'blender': (2, 80, 0),
   "description": "Starts debugging server for VS Code.",
   'location': 'In search (Edit > Operator Search) type "Debug"',
   "warning": "",
   "wiki_url": "https://github.com/AlansCodeLog/blender-debugger-for-vscode",
   "tracker_url": "https://github.com/AlansCodeLog/blender-debugger-for-vscode/issues",
   'category': 'Development',
}
Blender Version: 

blender 2.80.74 

Paths listed by `where python` or the corresponding command:

/home/detlef/Gamedev/BlenderEXE/blender-2.80-script/2.80/python/bin/python

## Notes:

ptvsd 4.2.9

No result, when I search for debug (spc/F3).

PS: I try to use it with Spacemac and dap-mode

**Comment by alanscodelog** [comment]
It appears just fine for me with the latest build (4fb441517251).

- Does the addon appear in the Add-ons list in the preferences?
   - If it doesn't, do you get any errors when you load it (check in the console, Menu > Window > Toggle System Console).
   - One possibility is you downloaded the zip from the releases section and tried to add it directly. It needs to be renamed (or at least this was the case in 2.79). Check the release notes for details.
- If it does appear is it enabled?
- And if it's enabled, in the python console panel, does typing `bpy.ops.debug.` then clicking autocomplete suggest `check_for_debugger` and `connect_debugger_vscode`?

**Comment by clawdelle** [comment]
Hi,
it is in preferences
![image](https://user-images.githubusercontent.com/9298560/59134608-10a96e00-897c-11e9-9134-8f257d3a1604.png)
not seen in autocomplete.
![image](https://user-images.githubusercontent.com/9298560/59134663-49e1de00-897c-11e9-8b7f-93cd7183929b.png)
Thank you for your response.

**Comment by clawdelle** [comment]
... and nothing in console
![image](https://user-images.githubusercontent.com/9298560/59134801-d55b6f00-897c-11e9-9971-fe3433672218.png)

**Comment by alanscodelog** [comment]
I think I found the problem. You seem to be using the 2.79 version (hence the little warning icon that says upgrade to 2.8). I forgot, but none of the releases work with 2.8 yet. The version that works with 2.8 is only on the [update-to-2.8](https://github.com/AlansCodeLog/blender-debugger-for-vscode/tree/update-to-2.8) branch, you'll have to git clone or download it from there. I didn't want to release it yet because the API hadn't stabilized. If I have some time I'll put together a beta release now that there's been an API freeze. 

What's strange is you list the addon version as 2.80 (which if it really is, means the upgrade warning shouldn't be there). I would try uninstalling it and re-installing to be sure you're trying the 2.8 version.

**Comment by clawdelle** [comment]
Thanks a lot!!
git checkout update-to-2.8
git pull  (was probably not necessarry)
did the trick. 
![image](https://user-images.githubusercontent.com/9298560/59146350-45094280-89ed-11e9-83bf-ff5e2cf2a553.png)
