### ISSUE TITLE
Readme needs update for 2.9 changes

### ISSUE THREAD

**Issue by SBRK** [AlansCodeLog/blender-debugger-for-vscode#18]
After installing the addon to Blender 2.90, the `Debug: Start Debug Server for VS Code` action doesn't show up in the Search menu.

**Comment by SBRK** [comment]
Turns out this is now hidden when `Developer Extras` is disabled in the preferences.

**Comment by SBRK** [comment]
Just a remark, but the readme should be updated. Spacebar is no longer the default for search (it is now F3) and the 2.90 particularity should probably be mentionned

**Comment by alanscodelog** [comment]
I'll look into it. I think it might be because the category of the addon is development. Does the addon itself still work though? Just so I know whether anything else needs updating. It's been a while since I've used Blender to be honest.

When I have a little time I'll look into what's causing this and update the readme.

**Comment by SBRK** [comment]
> I'll look into it. I think it might be because the category of the addon is development. Does the addon itself still work though? Just so I know whether anything else needs updating. It's been a while since I've used Blender to be honest.
> 
> When I have a little time I'll look into what's causing this and update the readme.

Yep, still working fine!
