### ISSUE TITLE
 can't find file option under preferences.

### ISSUE THREAD

**Issue by derrick-xwp** [AlansCodeLog/blender-debugger-for-vscode#23]
In Blender go to: User Preferences > File and set the path to Scripts

I can't find file option under preferences.

Blender seems install addon as zip file.

So do I need to zip my code then install it?

So how to debug?

**Comment by alanscodelog** [comment]
Looks like it's called File Paths now in 3.0 at least. Should be last entry on the list on the left in the User Preferences.

You should not install your addon normally. Just point Blender to the folder where you keep it. Blender will then load any addons in that folder automatically when you restart it. No need to zip or anything. It's like adding an additional folder apart from the normal one Blender unzips addons to.

Also please note it's been a while since I've used this. I try to maintain it and keep it working, but I have not properly checked it with 3.0 if that's what you're using.
